In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings_data = pd.read_csv('u.data', encoding='latin1', header=0, engine='python',sep='\t', names=["User_Id", "Movie_Id", "Rating", "Timestamp"])
items_data = pd.read_csv('u.item',encoding='latin1', header=0, engine='python',sep='|', names=["Movie_Id","movie_title","release_date","videorelease_date","IMDb_URL","unknown","Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy","Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western"])
users_data = pd.read_csv('user.user',encoding='latin1', header=0, engine='python',sep='|', names=["User_Id","age","gender","occupation","zipcode"])

Data PreProcessing

In [3]:
ratings_df = pd.DataFrame(ratings_data)
ratings_df = ratings_df.drop('Timestamp', axis=1)
items_df = pd.DataFrame(items_data)
items_df = items_df.drop(['release_date', 'videorelease_date',  'unknown'], axis=1)
users_df = pd.DataFrame(users_data)
users_df = users_df.drop(['zipcode','occupation'],axis=1)
#items_df


In [4]:
genre_df=items_df.drop(['Movie_Id', 'IMDb_URL'], axis=1)
genre_matrix=genre_df.values
#genre_df

In [5]:
#combined_df = pd.merge(ratings_df, users_df, on='User_Id')
#combined_df = pd.merge(combined_df, items_df, on='Movie_Id')
#print(combined_df)
#print(combined_df.columns)   

In [6]:
user_item_matrix = ratings_df.pivot(index='User_Id', columns='Movie_Id', values='Rating')
user_item_matrix.fillna(0, inplace=True)
#print(user_item_matrix)

Non-Negative Matrix Factorisation

In [7]:
#from sklearn.decomposition import NMF
#import numpy as np
#from scipy.sparse.linalg import svds
#from scipy.sparse import csr_matrix

# Assuming user_item_matrix is defined

# Convert user-item matrix to CSR format
#matrix_sparse_csr = csr_matrix(user_item_matrix)

# Number of latent factors
#k = 10

# Apply NMF
#model = NMF(n_components=k, init='random', random_state=42)
#user_factors = model.fit_transform(matrix_sparse_csr)
#item_factors = model.components_

# Reconstruct the user-item matrix
#final_matrix = np.dot(user_factors, item_factors)
#print(final_matrix)
#print(type(final_matrix))


Singular Value Decomposition

In [8]:
from scipy.sparse.linalg import svds
from scipy.sparse import csr_matrix

matrix_sparse_csr = csr_matrix(user_item_matrix)

k = 10

u, s, vt = svds(matrix_sparse_csr, k=k)

final_matrix = np.dot(u, np.dot(np.diag(s), vt))
print(final_matrix)
print(type(final_matrix))

[[ 4.25204675e+00  2.08644700e+00  1.29105941e+00 ... -8.39539471e-03
   1.98410372e-02  5.78772121e-02]
 [ 1.85298728e+00 -1.07304097e-01  1.63140719e-01 ...  1.05689177e-02
   2.40161236e-04 -1.41019252e-04]
 [-1.16700091e-01 -1.98725527e-02  9.20469305e-02 ...  1.96975747e-02
  -3.17732077e-03 -1.03339447e-02]
 ...
 [ 2.01284547e+00 -2.21248849e-02  2.95242272e-01 ... -8.51598317e-04
  -3.53967691e-03 -4.23170973e-03]
 [ 1.37042937e+00  1.17361446e-01 -4.41472736e-01 ...  1.44812394e-02
   2.00441121e-03 -2.93361945e-02]
 [ 1.73635347e+00  2.07782144e+00  1.01422641e+00 ... -9.34285128e-03
   2.62328960e-02  2.75075243e-02]]
<class 'numpy.ndarray'>


In [9]:
user_item_matrix_np = user_item_matrix.values

print(user_item_matrix_np)

[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [10]:
zero_indices = np.where(user_item_matrix_np == 0)

user_item_matrix_updated = user_item_matrix_np.copy()

user_item_matrix_updated[zero_indices] = final_matrix[zero_indices]

print(user_item_matrix_updated)

[[ 5.00000000e+00  3.00000000e+00  4.00000000e+00 ... -8.39539471e-03
   1.98410372e-02  5.78772121e-02]
 [ 4.00000000e+00 -1.07304097e-01  1.63140719e-01 ...  1.05689177e-02
   2.40161236e-04 -1.41019252e-04]
 [-1.16700091e-01 -1.98725527e-02  9.20469305e-02 ...  1.96975747e-02
  -3.17732077e-03 -1.03339447e-02]
 ...
 [ 5.00000000e+00 -2.21248849e-02  2.95242272e-01 ... -8.51598317e-04
  -3.53967691e-03 -4.23170973e-03]
 [ 1.37042937e+00  1.17361446e-01 -4.41472736e-01 ...  1.44812394e-02
   2.00441121e-03 -2.93361945e-02]
 [ 1.73635347e+00  5.00000000e+00  1.01422641e+00 ... -9.34285128e-03
   2.62328960e-02  2.75075243e-02]]


Finding Total NUmber of Zeros Replaced

In [11]:
num_zeros_original = np.sum(user_item_matrix_np == 0)

user_item_matrix_updated = user_item_matrix_np.copy()

zero_indices = np.where(user_item_matrix_np == 0)

user_item_matrix_updated[zero_indices] = final_matrix[zero_indices]

num_replaced = np.sum(user_item_matrix_np != user_item_matrix_updated)

print("Number of zeros in the original matrix:", num_zeros_original)
print("Number of values replaced:", num_replaced)

Number of zeros in the original matrix: 1486126
Number of values replaced: 1486126


Normalizing The Original Array With Min and Max Range

In [12]:
normalized_array = (user_item_matrix_updated - np.min(user_item_matrix_updated)) / (np.max(user_item_matrix_updated) - np.min(user_item_matrix_updated))
min_range = 1
max_range = 5
scaled_array = min_range + normalized_array * (max_range - min_range)
print("Original array:", user_item_matrix_updated)
print("Normalized array:", scaled_array)

Original array: [[ 5.00000000e+00  3.00000000e+00  4.00000000e+00 ... -8.39539471e-03
   1.98410372e-02  5.78772121e-02]
 [ 4.00000000e+00 -1.07304097e-01  1.63140719e-01 ...  1.05689177e-02
   2.40161236e-04 -1.41019252e-04]
 [-1.16700091e-01 -1.98725527e-02  9.20469305e-02 ...  1.96975747e-02
  -3.17732077e-03 -1.03339447e-02]
 ...
 [ 5.00000000e+00 -2.21248849e-02  2.95242272e-01 ... -8.51598317e-04
  -3.53967691e-03 -4.23170973e-03]
 [ 1.37042937e+00  1.17361446e-01 -4.41472736e-01 ...  1.44812394e-02
   2.00441121e-03 -2.93361945e-02]
 [ 1.73635347e+00  5.00000000e+00  1.01422641e+00 ... -9.34285128e-03
   2.62328960e-02  2.75075243e-02]]
Normalized array: [[4.38940913 3.55026279 3.96983596 ... 2.2880208  2.29986805 2.31582701]
 [3.96983596 2.24652136 2.35999275 ... 2.29597772 2.29164405 2.29148412]
 [2.24257906 2.28320529 2.33016371 ... 2.29980786 2.29021016 2.28720744]
 ...
 [4.38940913 2.28226028 2.41541902 ... 2.29118598 2.29005813 2.28976777]
 [2.86653868 2.340785   2.1063131

Adjuscent Cosine Similarity

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

# scaled_array is assumed to be your dataset

# Standardize the array
scaled_array = StandardScaler().fit_transform(scaled_array)

# Compute the mean of each item
item_means = scaled_array.mean(axis=0)

# Compute the adjusted scaled array by subtracting the mean from each item
adjusted_scaled_array = scaled_array - item_means

# Compute the adjusted cosine similarity matrix
item_similarity_matrix = cosine_similarity(adjusted_scaled_array.T)

print(item_similarity_matrix.shape)
print(item_similarity_matrix)

(1682, 1682)
[[ 1.          0.31800653  0.3264873  ... -0.12827065  0.04740076
   0.0500615 ]
 [ 0.31800653  1.          0.36543637 ... -0.04584622  0.13629031
   0.12954874]
 [ 0.3264873   0.36543637  1.         ... -0.04303403  0.03002813
   0.14269135]
 ...
 [-0.12827065 -0.04584622 -0.04303403 ...  1.         -0.01086667
  -0.022534  ]
 [ 0.04740076  0.13629031  0.03002813 ... -0.01086667  1.
   0.02446696]
 [ 0.0500615   0.12954874  0.14269135 ... -0.022534    0.02446696
   1.        ]]


Pearson Correlation

In [14]:
#from scipy.stats import pearsonr

 #scaled_array is assumed to be your dataset

 #Calculate Pearson correlation matrix
#correlation_matrix = np.corrcoef(scaled_array.T)

#print(correlation_matrix.shape)
#print(correlation_matrix)


Spearman correlation

In [15]:
#from scipy.stats import rankdata

# scaled_array is assumed to be your dataset

# Rank the data along each column
#ranked_data = np.apply_along_axis(rankdata, 0, scaled_array)

# Calculate Spearman correlation matrix
#item_similarity_matrix = np.corrcoef(ranked_data.T)

#print(item_similarity_matrix.shape)
#print(item_similarity_matrix)


Proximity Impact Popularity

In [16]:
popularity_ratings = np.mean(scaled_array, axis=0)
print(popularity_ratings)
print(popularity_ratings.shape)
similarity_weight = 0.5
popularity_weight = 0.5

weighted_similarity_matrix = similarity_weight * item_similarity_matrix + popularity_weight * popularity_ratings[:, np.newaxis]
print(weighted_similarity_matrix)
print(weighted_similarity_matrix.shape)

[ 8.25615056e-15 -2.34995245e-15  7.21138714e-15 ...  9.90667428e-14
  9.35772021e-16  3.49734381e-14]
(1682,)
[[ 0.5         0.15900326  0.16324365 ... -0.06413533  0.02370038
   0.02503075]
 [ 0.15900326  0.5         0.18271818 ... -0.02292311  0.06814515
   0.06477437]
 [ 0.16324365  0.18271818  0.5        ... -0.02151701  0.01501407
   0.07134568]
 ...
 [-0.06413533 -0.02292311 -0.02151701 ...  0.5        -0.00543333
  -0.011267  ]
 [ 0.02370038  0.06814515  0.01501407 ... -0.00543333  0.5
   0.01223348]
 [ 0.02503075  0.06477437  0.07134568 ... -0.011267    0.01223348
   0.5       ]]
(1682, 1682)


Finding All Similar Items

In [17]:
def find_all_similar_items(weighted_similarity_matrix):
    num_items = weighted_similarity_matrix.shape[0]
    all_similar_items_dict = {}

    for item_index in range(num_items):
        similarity_scores = weighted_similarity_matrix[item_index, :]
        
        similar_item_indices = np.argsort(similarity_scores)[::-1] + 1

        all_similar_items_dict[item_index + 1] = similar_item_indices

    return all_similar_items_dict

all_similar_items_dict = find_all_similar_items(weighted_similarity_matrix)

#for item_index, similar_items in all_similar_items_dict.items():
    #print(f"Item {item_index}: All Similar Items {similar_items}")


Movie Recommendation Sytem

In [18]:
def recommend_top_items(all_similar_items_dict, num_recommendations=15):
    top_recommendations_dict = {}

    for item_index, similar_items in all_similar_items_dict.items():
        
        recommended_items = [item for item in similar_items if item != item_index][:num_recommendations]

        top_recommendations_dict[item_index] = recommended_items

    return top_recommendations_dict

try:
    user_input = int(input("Enter movie ID to get recommendations: "))
except ValueError:
    print("Invalid input. Please enter a valid integer.")
    sys.exit(1)

if user_input not in all_similar_items_dict:
    print(f"Invalid movie ID: {user_input}")
else:
    top_recommendations_dict = recommend_top_items(all_similar_items_dict, num_recommendations=5)
    movie_title = items_df.loc[user_input - 1, 'movie_title']
    recommended_movie_titles = [items_df.loc[rec - 1, 'movie_title'] for rec in top_recommendations_dict[user_input]]

    print(f"Top 5 Recommendations for Movie '{movie_title}': {recommended_movie_titles}")

Top 5 Recommendations for Movie 'Toy Story (1995)': ['Willy Wonka and the Chocolate Factory (1971)', 'Independence Day (ID4) (1996)', 'Star Wars (1977)', 'Return of the Jedi (1983)', 'Mission: Impossible (1996)']


Widgets for Movies

In [19]:
# Create select box for movie titles
import ipywidgets as widgets

# Create select box for movie titles
movie_titles = ['-- Select Movie --'] + items_df['movie_title'].tolist()
movie_title_dropdown = widgets.Dropdown(options=movie_titles, description='Select a Movie:', value='-- Select Movie --')

def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        movie_title = change['new']
        if movie_title != '-- Select Movie --':
            movie_index = items_df.index[items_df['movie_title'] == movie_title].tolist()[0] + 1
            recommendations = recommend_top_items(all_similar_items_dict)[movie_index]
            recommended_movie_titles = [items_df.loc[rec - 1, 'movie_title'] for rec in recommendations]
            print(f"Top 5 Recommendations for Movie '{movie_title}': {recommended_movie_titles}")

movie_title_dropdown.observe(on_change)

display(movie_title_dropdown)


Dropdown(description='Select a Movie:', options=('-- Select Movie --', 'Toy Story (1995)', 'GoldenEye (1995)',…

Loading Pickle Files

In [20]:
#import pickle


#with open('user_item_matrix.pkl', 'wb') as f:
    #pickle.dump(user_item_matrix, f)

#with open('items_df.pkl', 'wb') as f:
    #pickle.dump(items_df, f)

#with open('all_similar_items_dict.pkl', 'wb') as f:
    #pickle.dump(all_similar_items_dict, f)

#with open('top_recommendations_dict.pkl', 'wb') as f:
    #pickle.dump(top_recommendations_dict, f)

# Save the model and necessary data structures into a pickle file
#with open('recommender_system.pickle', 'wb') as file:
    #pickle.dump({
        #'model': model,
        #'user_item_matrix': user_item_matrix,
        #'item_similarity_matrix': item_similarity_matrix,
        #'popularity_ratings': popularity_ratings,
        #'combined_df' : combined_df,
        #'items_df':items_df
    #}, file)

Example Code

In [21]:
import numpy as np
from scipy.sparse.linalg import svds
from scipy.sparse import csr_matrix

# User-Item Matrix
user_item_matrix = np.array([
    [3, 0, 0, 0, 0],
    [0, 0, 0, 2, 0],
    [0, 2, 5, 0, 0],
    [1, 0, 3, 5, 0],
    [4, 3, 0, 0, 3]
], dtype=float)  # Cast the matrix to float data type

# Convert to CSR matrix
matrix_sparse_csr = csr_matrix(user_item_matrix)
#print(matrix_sparse_csr)
# Number of singular values to compute
k = 2

# Perform SVD
u, s, vt = svds(matrix_sparse_csr, k=k)

# Reconstruct the matrix
final_matrix = np.dot(u, np.dot(np.diag(s), vt))

# Print the reconstructed matrix
print("Reconstructed Matrix:")
print(final_matrix)
print("Matrix Type:", type(final_matrix))


Reconstructed Matrix:
[[ 1.73652926  1.06684381  0.06700046 -0.13941483  1.01586054]
 [-0.09294322  0.06868232  0.96755329  0.8231338  -0.13857591]
 [ 0.82289664  0.89933773  3.07210321  2.48756553  0.2177702 ]
 [ 0.41348549  0.79311719  4.17815991  3.46269282 -0.11900574]
 [ 4.39807669  2.71159368  0.24394459 -0.29072683  2.56641355]]
Matrix Type: <class 'numpy.ndarray'>


Regular Expressions NLTK for Fetching Posters

In [22]:
import re
import requests

def fetch_poster_from_tmdb_by_title(movie_title):
    api_key = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMjEwZWEzOGJjNDhkZTQyZDQ1YzMzMzUxMGZkODI1MyIsInN1YiI6IjY1ZmQzMTFmMzc4MDYyMDE3ZTg3MWM2ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.ifEhqFnSL7MLwhmIbn7mMN0fwRdD6DmWTwmvkQpZqQQ'
    url = "https://api.themoviedb.org/3/search/movie"
    headers = {
        "accept": "application/json",
        "Authorization": f"Bearer {api_key}"
    }
    # Extract title and year from the input string using regular expressions
    match = re.match(r'^(.*?)\s*\((\d{4})\)$', movie_title)
    if match:
        title, year = match.groups()
    else:
        title = movie_title
        year = None
    
    params = {
        "query": title,
        "year": year,  # Add year as a parameter
        "include_adult": False,
        "language": "en-US",
        "page": 1
    }
    print("API Request Params:", params)
    response = requests.get(url, headers=headers, params=params)
    print("API Response:", response.json())
    data = response.json()
    if 'results' in data and data['results']:
        poster_path = data['results'][0].get('poster_path')
        if poster_path:
            base_url = "https://image.tmdb.org/t/p/w500"  # Adjust the size as needed
            poster_url = f"{base_url}{poster_path}"
            return poster_url
    return None

Making A Streamlit Web App Interface

In [23]:
import streamlit as st

def main():
    # Assuming you have items_df loaded
    selected_movie = st.selectbox("Select a Movie:", items_df['movie_title'].values)

    if st.button('Show Recommendations'):
        # Check if selected_movie is not '-- Select Movie --'
        if selected_movie != '-- Select Movie --':
            # Find movie_id corresponding to the selected movie title
            movie_id_candidates = items_df.loc[items_df['movie_title'] == selected_movie, 'Movie_Id'].values
            if len(movie_id_candidates) > 0:
                # If at least one movie_id is found, use the first one
                movie_id = movie_id_candidates[0]
                all_similar_items_dict = find_all_similar_items(weighted_similarity_matrix)
                recommendations = recommend_top_items(all_similar_items_dict)[movie_id]
                recommended_movie_titles = [items_df.loc[rec - 1, 'movie_title'] for rec in recommendations]
                st.write(f"Top 5 Recommendations for Movie '{selected_movie}': {recommended_movie_titles}")
                for title in recommended_movie_titles:
                    try:
                        poster_url = fetch_poster_from_tmdb_by_title(title)
                    except KeyError:
                        poster_url = None

                    if poster_url is not None:
                        st.image(poster_url, caption=title, use_column_width=True)
                    else:
                        st.write(f"No poster available for {title}")
            else:
                # If no movie_id is found, display a message
                st.write(f"No movie found with the title '{selected_movie}'.")
        else:
            # If '-- Select Movie --' is selected, display a message
            st.write("Please select a movie.")

if __name__ == "__main__":
    main()


2024-03-25 20:02:29.930 
  command:

    streamlit run c:\Users\moham\OneDrive\Desktop\pro\venv\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
